### ISSUE TITLE
FCN character segmentation

### ISSUE THREAD

**Issue by mrocr** [ray075hl/ray075hl.github.io#1]
@ray075hl Regarding the [`FCN character segmentation`](https://ray075hl.github.io/ray075hl.github.io/FCN-character-segmentation/) .

Can you post the full code along with some documentation.

**Comment by ray075hl** [comment]
Tell me your email address. I will post them to you.

**Comment by mrocr** [comment]
But why don't you create a repository for it, here at github?

Anyways, here is my email: christopher.edward@outlook.com

**Comment by ray075hl** [comment]
Part of the code's copyright belong to my company. So ...

**Comment by mrocr** [comment]
In the README file you posted, it states that it's required to download and install a repository that is no longer available, which is:

```
github.***/WarBe**/deep_c***_segm***
```
So, is deep_ch**_segm*** needed in order for the code to function and work?

**Comment by ray075hl** [comment]
The repository I post to you is  "deep_ch**_segm***".

**Comment by mrocr** [comment]
:smile: Thank you
